buf:
  build:
    context: .
    dockerfile: build/docker/buf.Dockerfile
    args:
      - GO_VERSION=${GO_VERSION}
      - BUF_VERSION=1.30.1
  working_dir: /usr/src/appstore-notify-sample
  volumes:
    - ./:/usr/src/appstore-notify-sample
